Fix some new PVS-Studio issues
GameProgressive/UniSpySDK pull request #28
Opened 2021-08-02 11:12 UTC by dimhotepus

Product page: https://www.viva64.com/en/pvs-studio/
How to use for free on open source projects: https://www.viva64.com/en/b/0600/

2021-08-02 11:22 UTC, dimhotepus commented on gstats/gstats.c
> +	resp[len] = '\0';
Looks like i made mistake and _**truncate**_ last byte every time.

Now should work as expected with 128 bytes max.

2021-08-02 20:36 UTC, dimhotepus commented on Chat/chatSocket.c
> +#include <stddef.h>
Buildfix

2021-08-06 08:47 UTC, dimhotepus commented
@arves100 Could you please take a look?

2021-08-06 22:41 UTC, arves100 commented
> @arves100 Could you please take a look?

will review them in some days, I was pretty unactive in this first days of august

2021-08-06 23:51 UTC, dimhotepus commented
> > @arves100 Could you please take a look?
> 
> will review them in some days, I was pretty unactive in this first days of august

No problem, we are not in a hurry. Thank you for review.

2021-09-15 20:06 UTC, arves100 requested changes

2021-09-15 20:08 UTC, arves100 commented
I'm terribly sorry for the delay in reviewing this commits, thank you for sending this pr and your patience! there are two issues there:
https://github.com/GameProgressive/UniSpySDK/pull/28/commits/0b8853ce6c8bad6fbdae2e9e1fbb03d1c649c176
https://github.com/GameProgressive/UniSpySDK/pull/28/commits/0f150812bf09331b48b76694d90a671de07d0be9

for the Github Actions I'm not sure how that works at the moment, I would prefer you sending another PR for migration to GitHub action if is possible so I could review it once I figure out how to use it.

2021-09-22 11:37 UTC, dimhotepus commented on ghttp/ghttpEncryption.c
> +#ifdef GSI_COMMON_DEBUG
@arves100  `gsDebugFormat` is defined either as empty macro when `GSI_COMMON_DEBUG` is not defined, or as actual debug format if `GSI_COMMON_DEBUG` is defined,  So both Release and Debug builds are ok.  Should i still wrap `gsDebugFormat` ?

2021-09-22 11:44 UTC, dimhotepus commented
> I'm terribly sorry for the delay in reviewing this commits, thank you for sending this pr and your patience! there are two issues there:
> [0b8853c](https://github.com/GameProgressive/UniSpySDK/commit/0b8853ce6c8bad6fbdae2e9e1fbb03d1c649c176)
> [0f15081](https://github.com/GameProgressive/UniSpySDK/commit/0f150812bf09331b48b76694d90a671de07d0be9)
> 
> for the Github Actions I'm not sure how that works at the moment, I would prefer you sending another PR for migration to GitHub action if is possible so I could review it once I figure out how to use it.

Removed Github Actions, wrote a note about `gsDebugFormat`.

2021-09-24 20:17 UTC, arves100 commented on ghttp/ghttpEncryption.c
> +#ifdef GSI_COMMON_DEBUG
GSI_COMMON_DEBUG is only be defined when there is a Debug build, Release would not include it. gsDebugFormat will be defined as an empty macro when a release build is happening, but guarding gsDebugFormat definitly doesn't hurt (and I would prefer to do so if it uses some variables like the ssl error)

2021-09-29 12:30 UTC, dimhotepus commented
> I'm terribly sorry for the delay in reviewing this commits, thank you for sending this pr and your patience! there are two issues there: [0b8853c](https://github.com/GameProgressive/UniSpySDK/commit/0b8853ce6c8bad6fbdae2e9e1fbb03d1c649c176) [0f15081](https://github.com/GameProgressive/UniSpySDK/commit/0f150812bf09331b48b76694d90a671de07d0be9)
> 
> for the Github Actions I'm not sure how that works at the moment, I would prefer you sending another PR for migration to GitHub action if is possible so I could review it once I figure out how to use it.

Fixed PR comments.

2021-09-29 13:08 UTC, arves100 approved these changes

2021-09-29 13:08 UTC, merged

2021-09-29 13:08 UTC, arves100 commented
Thanks for the pr!